default:
  gridlines_dict_type: 'standard'
  left_label: True
  right_label: False
  top_label: True
  bottom_label: False
  grid_lat_linewidth: 1
  grid_lon_linewidth: 1
  grid_lat_color: 'black'
  grid_lon_color: 'black'
  grid_lat_spacing: 'auto'
  grid_lon_spacing: 'auto'
  grid_lat_dashes: [4, 2]
  grid_lon_dashes: [4, 2]
  grid_lat_xoffset: null
  grid_lon_xoffset: null
  grid_lat_yoffset: null
  grid_lon_yoffset: null
  grid_lat_fontsize: null
  grid_lon_fontsize: null
