default:
  boundaries_dict_type: 'standard'
  request_coastlines: True
  request_countries: True
  request_states: True
  request_rivers: True
  
  coastlines_linewidth: 2
  countries_linewidth: 1
  states_linewidth: 0.5
  rivers_linewidth: 0
  
  coastlines_color: 'red'
  countries_color: 'red'
  states_color: 'red'
  rivers_color: 'red'
